### PR TITLE
Added logger.error instead of logger.debug in sendSimpleErrorResponse…

### PR DESCRIPTION
**Pull request by kishore25kumar**
This change helps to debug why something is failing from logs

### CODE REVIEW

**Comment by andrewgaul** [comment]
The debug level is correct; server processes should not log at error when sending an error condition to a client.  Instead error level is for errors within the server, e.g., could not allocate an expected resource, misconfiguration.

**Comment by kishore25kumar** [comment]
At least it should be info. With debug its really hard to find those kind of issues.

**Comment by andrewgaul** [comment]
Arguably this should be trace and not debug; by default server processes should not log individual requests.  We could add some formatting, e.g., `>>>` for requests and `<<<` for responses, to make this easier to match up.

**Comment by kishore25kumar** [comment]
I think without this logs it's very difficult to find out what is happening. As the errors returned by storage service are captured by s3proxy and are sent to the client. That's the reason I was thinking to add it which saves a lot of time. Even if we format the request response it very difficult to see logs and find what is the actual issue. If I enable debug there is a lot of logs printed in the console.

**Comment by andrewgaul** [comment]
I want to follow the following discipline for logging:

https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels

This states that individual response errors fall under the debug category.

**Pull request closed without merging**
