### PR TITLE
Add support for X-Amz-Expires parameter

### LINKED ISSUE #160: Support V4 Signed URLs
Current error:

```
E 10-18 13:06:32.338 S3Proxy-24 o.gaul.s3proxy.S3ProxyHandler:480 |::] Unknown parameters X-Amz-Expires with URI /temporary-bucket/68ae4a90-f079-02d1-6b06-fa3cd4e3aa26/c697097d-aad2-4d8c-293c-a4159f0a9286
```

Originally reported by @historus in #138.

### PR DESCRIPTION
**Pull request by andrewgaul**
Fixes #160.

### CODE REVIEW

**Comment by andrewgaul** [comment]
@historus Please verify locally since I lack a way to reproduce your symptoms.

**Comment by historus** [comment]
E 10-19 09:03:21.325 S3Proxy-16 o.gaul.s3proxy.S3ProxyHandler:486 |::] Unknown parameters X-Amz-Date with URI /temporary-bucket/0a05bbf2-b33d-dc49-b9ea-8ff341785bf0/ec36c5cd-6ee4-0b95-0921-b0fe3157c8b3

You should look at presigned URLs here: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

**Comment by andrewgaul** [comment]
Can you share *how* to reproduce this symptom?

**Comment by historus** [comment]
I actually do exactly what Amazon proposes:
http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURLJavaSDK.html

final GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(bucketName, objectKey);
final Instant tomorrow = LocalDateTime.now().plusDays(1).atZone(ZoneId.systemDefault()).toInstant();
request.setMethod(GET);
request.setExpiration(Date.from(tomorrow));
amazonS3Https.generatePresignedUrl(request);

and perform the download with this URL.

**Comment by andrewgaul** [comment]
OK, so this is actually a feature request for V4 signed URLs not a specific parameter.

**Pull request closed without merging**
