### PR TITLE
Add property to include permissive CORS response

### PR DESCRIPTION
**Pull request by andrewgaul**
References #142.

### CODE REVIEW

**Comment by andrewgaul** [comment]
@auguster Can you test this and see if it suits your use case?

**Comment by auguster** [comment]
With pleasure, How can I configure it ? I guess "*" would be enough for my tests.

**Comment by andrewgaul** [comment]
You need to add `s3proxy.cors-allow-all` to your properties file.  I can add more flexible configuration if you have feedback.

**Comment by andrewgaul** [comment]
@auguster Good to merge?

**Comment by auguster** [comment]
I'm testing it but it doesn't seem like the server sets place a `Access-Control-Allow-Origin: *` in the response header.
I'll try rebuilding it and retesting it (in case I did something wrong) but so far it's a no go...

**Comment by auguster** [comment]
Nope, I can't find any mention of `Access-Control-Allow-Origin` in the response header.

I did use `s3proxy.cors-allow-all=true` in my properties file. I don't know if s3proxy took it into consideration, I don't see any mention of it in the starting logs:
```
I 07-19 10:59:50.585 main org.eclipse.jetty.util.log:186 |::] Logging initialized @1485ms
I 07-19 10:59:50.638 main o.eclipse.jetty.server.Server:327 |::] jetty-9.2.z-SNAPSHOT
I 07-19 10:59:50.676 main o.e.j.server.ServerConnector:266 |::] Started ServerConnector@6fecc906{HTTP/1.1}{0.0.0.0:8080}
I 07-19 10:59:50.677 main o.eclipse.jetty.server.Server:379 |::] Started @1580ms
```

**Comment by andrewgaul** [comment]
@auguster Could you retest with the latest commits in this branch?  Previously it had the wrong behavior for anonymous requests.

**Comment by auguster** [comment]
Now I do see the `Access-Control-Allow-Origin:*`.

For some strange reason what I wanted to do still fails. I'm trying to grab a frame from a video (hosted on s3proxy) and display it using nothing but HTML5 and javascript. I can grab the frame but I cannot export the grabbed frame because "Tainted canvases may not be exported.". Normally having `Access-Control-Allow-Origin:*` on the video should have solved that but doesn't seem to be the case.

But it's not really related to this pull request anymore. So it's good to merge ;-)

**Comment by auguster** [comment]
Never minded, I forgot to set the attribute `crossorigin="anonymous"` on the video element. Now everything works great ;)

**Comment by andrewgaul** [comment]
Thanks for your feedback @auguster!

**Pull request merged**
